name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          python-version: 3.14
          use-mamba: true

      # Ensure env is active for all subsequent steps
      - name: Initialize shell for conda
        shell: bash -l {0}
        run: |
          conda info
          conda list

      # Install package into the env 
      - name: Install package
        shell: bash -l {0}
        run: |
          conda install -c conda-forge unidep=3
          unidep install -n pynlo .
          conda activate pynlo

      - name: Install testing dependencies
        shell: bash -l {0}
        run: |
          pip install pytest

      - name: Run tests
        shell: bash -l {0}
        run: pytest -v